### ISSUE TITLE
与rename-file冲突

### ISSUE THREAD

**Issue by jimmy2011617** [evgo2017/picgo-plugin-folder-name#1]
同时安装folder-name与rename-file时folder-name隐藏path规则不起作用，不知到底那个插件影响那个

**Comment by evgo2017** [comment]
@jimmy2011617 都在 beforeUploadPlugins 时有处理，应该和两个插件的执行顺序有关。

**Comment by evgo2017** [comment]
@jimmy2011617  我更新了文档，你可以参考示例，结合两款插件分别使用各自特性。
