### ISSUE TITLE
为什么开启了插件后上传路径未改变？

### ISSUE THREAD

**Issue by BurgessX** [evgo2017/picgo-plugin-folder-name#2]
我的测试文件 test.md 位置为 D:\Users\Lenovo\Desktop\test.md，在 Typora 的 `偏好设置` -> `图像` 中，不管是

1. 开启了 `插入图片时自动上传` 然后在文档中粘贴图片，还是
2. 不开启自动上传然后在粘贴完图片后右键手动上传，

这两种方式 PicGo 返回的 URL 都没有包含父文件夹名称。我已经在插件中设置 `向上层数` 为1，`忽略名称` 没有填写，如图：

![image](https://user-images.githubusercontent.com/52914833/114348648-66af5400-9b99-11eb-8479-10f2b373617d.png)

所以我想这样设置后，PicGo 上传的路径应该为类似 `https://cdn.jsdelivr.net/gh/burgessx/imgbed@main/img/Desktop/20210412134726.png` 才对，然而实际上为 `https://cdn.jsdelivr.net/gh/burgessx/imgbed@main/img/20210412134726.png`。

下面是我的一种 Typora 设置：

![image](https://user-images.githubusercontent.com/52914833/114347416-7d54ab80-9b97-11eb-8211-6af66ecf0a07.png)

初次使用 PicGo，望不吝赐教，感谢~

**Comment by evgo2017** [comment]
@BurgessX 你好，我更新了插件文档。我看着你的设置没有什么问题，你参考下示例，也可以调整下两个参数，看看路径变化。如果还有问题我再看看。

**Comment by BurgessX** [comment]
> @BurgessX 你好，我更新了插件文档。我看着你的设置没有什么问题，你参考下示例，也可以调整下两个参数，看看路径变化。如果还有问题我再看看。

还是不行，可能是 Typora 的目录结构也得调整成和你一样，也就是说图片和文章要放在一起。但我不喜欢那种目录结构。

**Comment by BurgessX** [comment]
经过测试，Typora 的偏好设置中设置复制图片到 `./${filename}.assets` 文件夹，然后在 Typora 中粘贴一张图片，然后右键上传，图片 URL 为 `https://cdn.jsdelivr.net/gh/burgessx/imgbed@main/img/20210419172126.png`，仍然没有包含目录名称。

**Comment by evgo2017** [comment]
@BurgessX 不用一样。你改插件参数，看看上传后的变化。

**Comment by BurgessX** [comment]
> @BurgessX 不用一样。你改插件参数，看看上传后的变化。

一层两层都试过了，都是一样的结果。

**Comment by evgo2017** [comment]
@BurgessX  ① 两个参数都改，根据示例，如果都一样，② 确认开了插件，图片上传区可以试试。

**Comment by BurgessX** [comment]
我知道问题出在哪了，PicGo中的`PicGo设置`中的`时间戳重命名`如果启用，则此插件会失效。另外，我今天突然不想用文件夹分类了2333

**Comment by evgo2017** [comment]
@BurgessX 知道原因就好。看来我丢失了一个用户 (T_T) 555
